### ISSUE TITLE
Should use OpenUG

### ISSUE THREAD

**Issue by AndrewCarterUK** [symfonyuk/symfonyuk#1]
Should use [OpenUG](https://github.com/OpenUG/OpenUG) (because all Symfony user groups should have websites made primarily using Zend components).

P.S. The slideshow ate my CPU like it was candy floss

**Comment by jakzal** [comment]
:trollface:

**Comment by AndrewCarterUK** [comment]
Can you add the improvement label?

**Comment by sroze** [comment]
:dancer:
